### ISSUE TITLE
RPCFailedError: The remote RPC to the application server failed for call taskqueue.BulkAdd()

### ISSUE THREAD

**Issue by speedplane** [GoogleCloudPlatform/python-runtime#23]
I am sporadically getting the following error when using the deferred library to add a task to the taskqueue. I am running on the App Engine Flexible / Managed VM environment using the `gcr.io/google_appengine/python-compat-multicore` Docker image. This [SO post seems to describe](http://stackoverflow.com/questions/34078742/undocumented-managed-vm-task-queue-rpcfailederror) a similar issue, but does not have much more information.

Any thoughts?

```
Traceback (most recent call last):
  ...
  File "/home/vmagent/app/libs/../updater/CrossPlatform.py", line 589, in Defer
    defer.defer(fn_to_run, *args, **kwargs)
  File "/home/vmagent/app/defer/api.py", line 12, in defer
    default_backend(func, args, kwargs, **config)
  File "/home/vmagent/app/defer/backends/appengine.py", line 12, in defer
    gae_defer(func, *args, **kwargs)
  File "/env/local/lib/python2.7/site-packages/google/appengine/ext/deferred/deferred.py", line 269, in defer
    return task.add(queue, transactional=transactional)
  File "/env/local/lib/python2.7/site-packages/google/appengine/api/taskqueue/taskqueue.py", line 1134, in add
    return self.add_async(queue_name, transactional).get_result()
  File "/env/local/lib/python2.7/site-packages/google/appengine/api/apiproxy_stub_map.py", line 613, in get_result
    return self.__get_result_hook(self)
  File "/env/local/lib/python2.7/site-packages/google/appengine/api/taskqueue/taskqueue.py", line 1948, in ResultHook
    rpc.check_success()
  File "/env/local/lib/python2.7/site-packages/google/appengine/api/apiproxy_stub_map.py", line 579, in check_success
    self.__rpc.CheckSuccess()
  File "/env/local/lib/python2.7/site-packages/google/appengine/ext/vmruntime/vmstub.py", line 312, in _WaitImpl
    raise self._ErrorException(*_DEFAULT_EXCEPTION)
RPCFailedError: The remote RPC to the application server failed for call taskqueue.BulkAdd().
```

**Comment by jonparrott** [comment]
Can you file this issue over at https://github.com/GoogleCloudPlatform/python-compat-runtime? This runtime doesn't provide or support the `google.appengine` APIs.
